### ISSUE TITLE
When more than one install XML is found, the one in the root of the ZIP should take precedence

### ISSUE THREAD

**Issue by chrisdeeming** [Xon/XenForo-AddOnInstaller#31]
I would imagine that most cases where more than one XML exists, the one in the root is more correct, so we should attempt to always use that one for install/upgrade.

**Comment by chrisdeeming** [comment]
I have committed a potential fix for this, though I haven't tested it yet. It's rather simplistic, but it should cover most cases. If someone could give it a try that'd be appreciated.

**Comment by chrisdeeming** [comment]
Heh, I just spotted the `break` in the code 🙄  So this isn't doing anything more than is already happening.

I'll have to take a closer look later.

**Comment by Xon** [comment]
@chrisdeeming I think getFileListing may be returning a weirdly sorted file list.

**Comment by Xon** [comment]
@chrisdeeming as near as I can tell; this should have only gotten the first valid XML file from the root directory. perhaps a version old beta version that was never upgraded?

**Comment by Xon** [comment]
After a bit of testing; I think I've figured it out.

If the XML file in the root folder is named correctly, it can come after the 1st folder. Basically [RecursiveIteratorIterator($dir, RecursiveIteratorIterator::SELF_FIRST);](https://github.com/Xon/XenForo-AddOnInstaller/blob/master/upload/library/AddOnInstaller/XenForo/Model/AddOn.php#L215) is named poorly.

**Comment by Xon** [comment]
I've semi-fixed this by adding path sorting in https://github.com/Xon/XenForo-AddOnInstaller/commit/8f3ab486cb5b7910c219ca0c4e82c3c402d2b97e but this is just string-based sorting, and really needs to be replaced by better iterating over the resultset so files are added first, and then directories.

**Comment by Xon** [comment]
1.3.5 tag/release has a stable file sort by directory for locating the XML file. Deployed into my live enviroment, and has handled a few add-ons already.

**Comment by chrisdeeming** [comment]
Good work. I was going to look into this last night myself - then my MacBook totally died. Back up and running today.

I'll leave it a day or two and then do the release at XF.com.

**Comment by Xon** [comment]
@chrisdeeming This isn't fully a breath 1st search so it may not work 100% as expected if they have a weird folder layout, but it does prefer the root folder now. I might fiddle with that before a 1.3.5 release
