### ISSUE TITLE
Faster Installer - only rebuild cached changes

### ISSUE THREAD

**Issue by Xon** [Xon/XenForo-AddOnInstaller#32]
@NixFifty 

The merged branch has issues if you install multiple add-on at once, it just keeps looping and doesn't finish in the "Rebuilding... Templates" phase.

I believe the issue is reparseNamedTemplates is called with a list of template names which it applies to each style.

Except the list of template names is replaced with a key/value list of templates, and the template is removed once it is processed on a single style.

**Comment by aakifn** [comment]
Batches seem to work well now, _I think_.
